name: Aqua
on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:   
jobs:
  test:
    name: Aqua scanner
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pipeline enforcer
        uses: aquasecurity/pipeline-enforcer-action@main
        with:
         aqua-key: ${{ secrets.AQUA_KEY }}
         aqua-secret: ${{ secrets.AQUA_SECRET }}

      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner:latest
        with:
          args: trivy fs --debug --sast --reachability --scanners misconfig,vuln,secret --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 .
env:
    AQUA_KEY: ${{ secrets.AQUA_KEY }}
    AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
    GITHUB_TOKEN: ${{ secrets.TOKEN }}
    TRIVY_RUN_AS_PLUGIN: 'aqua'
    ACTIONS_RUNTIME_TOKEN: ${{ secrets.TOKEN }}   
    TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
    TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }} 
